
const SPOTIFY_API_BASE = 'https://api.spotify.com/v1';

export async function fetchRecentlyPlayed(token: string, limit: number = 50) {
    const res = await fetch(`${SPOTIFY_API_BASE}/me/player/recently-played?limit=${limit}`, {
        headers: { Authorization: `Bearer ${token}` }
    });
    if (!res.ok) throw new Error('Failed to fetch recently played');
    return res.json();
}

export async function fetchAudioFeatures(token: string, ids: string[]) {
    // Spotify allows max 100 IDs per request
    const chunks = [];
    for (let i = 0; i < ids.length; i += 100) {
        chunks.push(ids.slice(i, i + 100));
    }

    let allFeatures: any[] = [];

    for (const chunk of chunks) {
        const res = await fetch(`${SPOTIFY_API_BASE}/audio-features?ids=${chunk.join(',')}`, {
            headers: { Authorization: `Bearer ${token}` }
        });
        if (res.ok) {
            const data = await res.json();
            allFeatures = [...allFeatures, ...data.audio_features];
        }
    }

    return allFeatures;
}

export async function createPlaylist(token: string, userId: string, name: string, trackUris: string[]) {
    // 1. Create Playlist
    const createRes = await fetch(`${SPOTIFY_API_BASE}/users/${userId}/playlists`, {
        method: 'POST',
        headers: {
            Authorization: `Bearer ${token}`,
            'Content-Type': 'application/json'
        },
        body: JSON.stringify({
            name: name,
            description: "Generated by MoodTrack based on your emotional resonance.",
            public: false
        })
    });

    if (!createRes.ok) throw new Error('Failed to create playlist');
    const playlist = await createRes.json();

    // 2. Add Tracks
    if (trackUris.length > 0) {
        await fetch(`${SPOTIFY_API_BASE}/playlists/${playlist.id}/tracks`, {
            method: 'POST',
            headers: {
                Authorization: `Bearer ${token}`,
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({
                uris: trackUris
            })
        });
    }

    return playlist;
}

export async function fetchRecommendations(token: string, seedTracks: string[], targetValence: number, targetEnergy: number, targetAcousticness?: number, limit: number = 20) {
    const seeds = seedTracks.slice(0, 5).join(','); // Max 5 seeds
    let url = `${SPOTIFY_API_BASE}/recommendations?seed_tracks=${seeds}&target_valence=${targetValence}&target_energy=${targetEnergy}&limit=${limit}`;
    if (targetAcousticness !== undefined) {
        url += `&target_acousticness=${targetAcousticness}`;
    }
    const res = await fetch(url, {
        headers: { Authorization: `Bearer ${token}` }
    });
    if (res.ok) return res.json();
    return null;
}
